config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  has_many :comments, as: :commentable, dependent: :destroy

  after_create_commit -> { broadcast_prepend_later_to commentable, target: ActionView::RecordIdentifier.dom_id(commentable, :comments), partial: "comments/comment_with_replies", locals: {comment: self}}
  after_update_commit -> { broadcast_replace_later }
  #after_destroy_commit -> { broadcast_remove }
  after_destroy_commit -> { broadcast_remove_to self, target: ActionView::RecordIdentifier.dom_id(self, :with_replies) }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable

  def index
  end

  def create
    @comment = Comment.create(comment_params)
  end

  private

  def set_commentable
    @commentable = GlobalID::Locator.locate_signed(params[:commentable])
  end

  def comment_params
    params.require(:comment).permit(:body).merge(commentable: @commentable)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= simple_format comment.body, id: dom_id(comment) %>

app/views/comments/_comment_with_replies.html.erb
<%= tag.div id: dom_id(comment, :with_replies) do %>
  <%= render comment %>

  <%# Actions %>
  <div>
    <%= link_to "Reply", new_comment_path(commentable: comment.to_sgid), data: {turbo_frame: dom_id(comment, :reply)} %>
  </div>

  <%# Nested comments %>
  <div style="margin-left:3rem;">
    <%= turbo_frame_tag :reply, comment %>

    <%= render partial: "comments/comments", locals: {commentable: comment} %>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<%= turbo_frame_tag commentable, :comments do %>
  <%= turbo_stream_from commentable %>
  <%= tag.div id: dom_id(commentable, :comments) do %>
    <%= render partial: "comments/comment_with_replies", collection: commentable.comments, as: :comment %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: Comment.new, url: comments_path(commentable: commentable.to_sgid), id: dom_id(commentable, :comment_form) do |form| %>
  <div>
    <%= form.text_area :body, required: true %>
  </div>
  <div>
    <%= form.submit %>
    <%= button_tag "Cancel", onclick: "this.closest('turbo-frame').replaceChildren()" if local_assigns[:cancel] %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%#= turbo_stream.append(dom_id(@commentable, :comments), partial: "comments/comment_with_replies", locals: { comment: @comment }) %>

<%# Replies can close the comment form %>
<% if @commentable.is_a? Comment %>
  <%= turbo_stream.replace dom_id(@commentable, :comment_form), "" %>
<% else %>
  <%= turbo_stream_action_tag :reset_form, target: dom_id(@commentable, :comment_form) %>
<% end %>

app/views/comments/index.html.erb
<%= render partial: "comments/comments", locals: {commentable: @commentable} %>

app/views/comments/new.html.erb
<%= turbo_frame_tag :reply, @commentable do %>
  <%= render partial: "comments/form", locals: {commentable: @commentable, cancel: true} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboComments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<h3>Discussion</h3>
<%= render partial: "comments/form", locals: {commentable: @post} %>
<%= turbo_frame_tag @post, :comments, src: comments_path(commentable: @post.to_sgid) %>